configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lightfield%2Flightfield-5a8ed2662a375dc2e30f8f80986dc5acd3ecf1dffd3aef39860eb6a40d2d57ec.yml
openapi_spec_hash: 651ab06b3f589f2a2ac6f91e0edcc3fa
config_hash: 92b5c2c73d27c94292a7e827cbb74e4b
